name: causal-bald
channels:
  - pytorch
  - gpytorch
  - defaults
dependencies:
  - black>=19.1
  - pip>=21.2
  - python=3.9
  - jupyter=1.0.0
  - pytorch=1.10.0
  - gpytorch=1.5.1
  - cudatoolkit=10.2
